service: sf-microblog
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  environment:
    DOMAIN_PREFIX: ${self:service}-${opt:stage, self:provider.stage, 'dev'}
    COMMENTS_TABLE: ${env:DOMAIN_PREFIX}-comments-table
    COGNITO_USER_POOL: ${env:DOMAIN_PREFIX}-user-pool
  httpApi:
    authorizers:
      userPoolAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: 
          Fn::Join:
          - ''
          - - 'https://cognito-idp.'
            - '${opt:region, self:provider.region}'
            - '.amazonaws.com/'
            - Ref: userPool
        audience:
          - Ref: userPoolClient

functions:
  posts:
    handler: microblog.handlers.posts
    events:
      - httpApi:
          path: /post
          method: GET
      - httpApi:
          path: /post
          method: POST
          authorizer: userPoolAuthorizer
      - httpApi:
          path: /post/{id}
          method: GET
      - httpApi:
          path: /post/{id}
          method: PUT
          authorizer: userPoolAuthorizer
      - httpApi:
          path: /post/{id}
          method: DELETE
          authorizer: userPoolAuthorizer
  comment:
    handler: microblog.handlers.comment
    events:
      - httpApi:
          path: /comment
          method: POST
          authorizer: userPoolAuthorizer
      - httpApi:
          path: /comment/{id}
          method: PUT
          authorizer: userPoolAuthorizer
      - httpApi:
          path: /comment/{id}
          method: DELETE
          authorizer: userPoolAuthorizer
  user:
    handler: microblog.handlers.user
    events:
      - httpApi:
          path: /user
          method: GET
          authorizer: userPoolAuthorizer
      - httpApi:
          path: /user
          method: PUT
          authorizer: userPoolAuthorizer
      - httpApi:
          path: /user/{username}
          method: GET

resources:
  Resources:
    HttpApi:
      Type: 'AWS::ApiGatewayV2::Api'
      DependsOn: userPool
    userPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: ${env:COGNITO_USER_POOL}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    userPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: {$env:DOMAIN_PREFIX}-user-pool-client
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: userPool
        CallbackURLs: 
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders: 
          - COGNITO
    userPoolDomain:
      Type: 'AWS::Cognito::UserPoolDomain'
      Properties:
        UserPoolId: 
          Ref: userPool
        Domain: ${env:DOMAIN_PREFIX}-user-pool-domain
